config/routes.rb
Mahbucket::Engine.routes.draw do
  root to: 'items#index'

  resources :items

  resources :tags, as: :acts_as_taggable_on_tag

  get '/search', to: 'search#search'
end

app/models/mahbucket/application_record.rb
module Mahbucket
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/mahbucket/item.rb
module Mahbucket
  class Item < ApplicationRecord
    self.table_name = :items

    # has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
    has_attached_file :file, styles: lambda { |attachment|
      if attachment.instance.image?
        { display: '800x800>', small: '400x400>', thumbnail: '100x100>' }
      else
        {}
      end
    }
  
    # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
    do_not_validate_attachment_file_type :file
    # Tagging
    acts_as_taggable
  
    validates_uniqueness_of :file_fingerprint,
      message: 'Error: This file has already been uploaded - please try searching for it by filename or by tag.'
    # TODO: link to previous upload (find by fingerprint)
  
    # Check to see if the file is an image before generating thumbnails etc
    before_post_process :image?
    def image?
      file_content_type =~ %r{^(image|(x-)?application)/(bmp|gif|jpeg|jpg|pjpeg|png|x-png)$}
    end
  end  
end

app/controllers/mahbucket/application_controller.rb
module Mahbucket
  # Application controller
  class ApplicationController < ActionController::Base
    include ::ActionController::Cookies

    protect_from_forgery with: :exception

    before_action :check_permitted_ips
    before_action :authenticate

    def self.permitted_ips_from_env
      ENV['PERMITTED_IPS']
    end

    private

    def check_permitted_ips
      return if Rails.env.development?
      return if self.class.permitted_ips_from_env.blank?

      ip_addresses = list_of_permitted_ips( self.class.permitted_ips_from_env )
      return if ip_addresses.include? request.ip

      render plain: 'Access Denied', status: :unauthorized
    end

    def list_of_permitted_ips( ip_list_from_env )
      # Remove anything inside brackets - e.g. '127.0.0.1 (localhost)' -> '127.0.0.1 '
      permitted_ips = ip_list_from_env.gsub( /{\([^)]+\)/, '' )

      # Handle the simple case (not multiline, no #comments embedded)
      return permitted_ips.split( /[, ]+/ ) unless permitted_ips.match?( /[\n#]/ )

      # Handle multi-line and/or comments
      handle_ip_list_with_comments( permitted_ips )
    end

    def handle_ip_list_with_comments( permitted_ips )
      permitted_ips_lines = permitted_ips.split( "\n" )

      ip_addresses = []
      permitted_ips_lines.each do |line|
        matches = line.match( /^(?<ip_address>[a-f\d.:]+)[#\s]?.*$/ )
        ip_addresses << matches['ip_address'] if matches['ip_address'].present?
      end

      ip_addresses
    end

    def authenticate
      @current_user = Mahbucket.config.authorize_request.call request
      @logged_in = (not @current_user.nil?)

      unless @logged_in
        redirect_to "/login?next=/mahbot/"
      else
        @user_courses_count = @current_user.first_user_course.count
      end
    end
  end
end

app/controllers/mahbucket/items_controller.rb
module Mahbucket
  class ItemsController < ApplicationController
    before_action :set_item, only: %i[ show edit update destroy ]
  
    # GET /items
    # GET /items.json
    def index
      @items = Item.where(user_id: @current_user.id)
        .order(created_at: :desc)
        .paginate(page: params[:page], per_page: 30)

      render layout: 'nt_layout'
    end
  
    # GET /items/1
    # GET /items/1.json
    def show
      render layout: 'nt_layout'
    end
  
    # GET /items/new
    def new
      @item = Item.new
      render layout: 'nt_layout'
    end
  
    # POST /items
    # POST /items.json
    def create
      @item = Item.new(item_params.merge(user_id: @current_user.id))
  
      respond_to do |format|
        if @item.save
          format.html { redirect_to @item, notice: 'Item was created.', layout: 'nt_layout'}
          format.json { render :show, status: :created, location: @item }
        else
          format.html { render :new, layout: 'nt_layout' }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # GET /items/1/edit
    def edit
      render layout: 'nt_layout'
    end
  
    # PATCH/PUT /items/1
    # PATCH/PUT /items/1.json
    def update
      respond_to do |format|
        if @item.update(item_params)
          format.html { redirect_to @item, notice: 'Item was updated.' }
          format.json { render :show, status: :ok, location: @item }
        else
          format.html { render :edit }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /items/1
    # DELETE /items/1.json
    def destroy
      @item.destroy
      respond_to do |format|
        format.html { redirect_to items_url, notice: 'Item was deleted.' }
        format.json { head :no_content }
      end
    end
  
    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end
  
    # Never trust parameters from the Internet, only allow the whitelist through
    def item_params
      params.require( :item ).permit( :file, :tag_list )
    end
  end
  
end

app/controllers/mahbucket/search_controller.rb
module MahBucket
  # Search controller
  class SearchController < ApplicationController
    def search
      if params[:q].present?
        @tag_results = ActsAsTaggableOn::Tag.where( 'name ilike ?', "%#{params[:q]}%" ).order( :name )
        @filename_results = Item.where( 'file_file_name ilike ?', "%#{params[:q]}%" ).order( :file_file_name )
      end
    end
  end
end

app/controllers/mahbucket/tags_controller.rb
module Mahbucket
  # Tag controller
  class TagsController < ApplicationController
    # GET /tags
    # GET /tags.json
    def index
      @tags = ActsAsTaggableOn::Tag.all.order( :name )
      render layout: 'nt_layout'
    end

    def tag_cloud
      @tags = Item.tag_counts_on( :customs )
      render layout: 'nt_layout'
    end

    # GET /tags/1
    # GET /tags/1.json
    def show
      @tag = ActsAsTaggableOn::Tag.find( params[:id] )
      render layout: 'nt_layout'
    end
  end
end

app/helpers/mahbucket/application_helper.rb
module Mahbucket
  module ApplicationHelper
    def theme
      Rails.application.secrets.theme
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render "layouts/themes/#{theme}/head" %>
  </head>

  <body>
    <%= render "layouts/themes/#{theme}/header" %>

    <%= yield %>

    <%= render "layouts/themes/#{theme}/footer" %>
  </body>
</html>

app/views/layouts/themes/38degrees/_head.html.erb
 <title>Library - 38 Degrees</title>
 

app/views/layouts/themes/38degrees/_header.html.erb
<p>
  <%= image_tag "/themes/#{theme}/images/38degrees-orange.png", height: 50 %>
</p>
<p id="notice">
  <%= notice %>
</p>
<p>
  <%= link_to 'View files', '/' %> |
  <%= link_to 'Add new file', new_item_path %> |
  <%= link_to 'Tags', '/tags' %> |
  <%= link_to 'Search', '/search' %>
</p>

app/views/layouts/themes/default/_head.html.erb
<title>Mah Bucket!!</title>

app/views/layouts/themes/default/_header.html.erb
<h1>Mah Bucket!</h1>

<p id="notice"><%= notice %></p>

<p>[ <%= link_to :files, '/' %> | <%= link_to :tags, '/tags' %> | <%= link_to :search, '/search' %> ]</p>

app/views/mahbucket/items/_form.html.erb
<%= form_for item, html: { multipart: true } do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label      :file %>
    <%= f.file_field :file %>
  </div>

  <div class="field">
    <%= f.label      :tag_list %>
    <%= f.text_field :tag_list, value: item.tag_list.join(', ') %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mahbucket/items/_item.html.erb
<div style="float: left; width: 180px; min-height: 160px; margin: 10px; overflow: hidden;">
  <% if item.image? %>
  <%= link_to item do %><%= image_tag item.file.url( :thumbnail, false ) %><% end %>
  <% else %>
  <%= link_to item do %><%= image_tag "/themes/#{theme}/images/default-file-icon.png" %><% end %>
  <% end %>
  <br>
  <%= link_to item do %><%= item.file_file_name %><% end %>
  <br>
  <%= link_to 'Show',   item %>
  <%= link_to 'Edit',   edit_item_path(item) %>
  <%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/mahbucket/items/edit.html.erb
<h1>Editing file: <%= @item.file_file_name %></h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/mahbucket/items/index.html.erb
<% if @items.present? %>

<% @items.each do |item| %>
<%= render partial: 'item', locals: { item: item } %>
<% end %>

<div style="clear: both;"></div>

<%= will_paginate @items %>

<% else %>

<p>
    You have not added any items yet.
</p>

<% end %>

<br>

<%= button_to 'Upload new file', new_item_path, method: :get %>

app/views/mahbucket/items/new.html.erb
<h1>Add new file</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/mahbucket/items/show.html.erb
<p>
  <strong>Filename:</strong>
  <%= @item.file_file_name %>
</p>
<p>
  <% if @item.image? %>
  <%= image_tag @item.file.url( :display, false ) %>
  <% else %>
  <%= image_tag "/themes/#{theme}/images/default-file-icon.png" %>
  <% end %>
</p>
<p>
  Tags: <% @item.tags.each do |tag| %>
    <%= link_to( tag.name, tag ) %><%= ', ' unless tag == @item.tags.last %>
    <% end %>
</p>

<p>
  <% if @item.image? %>Original (<%= @item.file.width %>x<%= @item.file.height %>):<% else %>Link:<% end %>
  <input type="text" size="100" value="<%= @item.file.url( 'original', false ) %>">
</p>
<% if @item.image? %>
  <% @item.file.styles.each do |style,style_obj| %>
  <p>
    <%= style.capitalize %> (<%= @item.file.width(style) %>x<%= @item.file.height(style) %>):
    <input type="text" size="100" value="<%= @item.file.url( style, false ) %>">
  </p>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/mahbucket/search/search.html.erb
<h1>
  Search
</h1>

<p>
  <%= form_tag '/search', method: :get do %>
    <%= search_field_tag 'q' %>
    <%= button_tag 'Search', name: '' %>
  <% end %>
</p>

<% unless @tag_results.blank? %>
<h3>
  Tags
</h3>
<p>
  <% @tag_results.each do |tag| %>
    <%= link_to tag.name, tag %><%= ', ' unless tag == @tag_results.last %>
  <% end %>
</p>
<% end %>

<% unless @filename_results.blank? %>
<br>
<h3>
  Files
</h3>
<p>
  <% @filename_results.each do |item| %>
    <%= render partial: 'items/item', locals: { item: item } %>
  <% end %>
</p>
<% end %>

<div style="clear: both;"></div>

app/views/mahbucket/tags/index.html.erb
<h1>Tags</h1>

<p>
  <%= form_tag '/search', method: :get do %>
    <%= search_field_tag 'q' %>
    <%= button_tag 'Search', name: '' %>
  <% end %>
</p>

<p>
  <% @tags.each do |tag| %>
    <%= link_to tag.name, tag %>,
  <% end %>
</p>

<%# tag_cloud( @tags, %w( css1 css2 css3 css4 ) ) do |tag, css_class| %>
  <%#= link_to tag.name, { :action => :show, :id => tag.name }, :class => css_class %>
<%# end %>

app/views/mahbucket/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @tag.name %>
</p>
<p>
  <% Mahbucket::Item.tagged_with( @tag.name ).each do |item| %>
    <%= render partial: 'mahbucket/items/item', locals: { item: item } %>
  <% end %>
</p>

<div style="clear: both;"></div>

<%= link_to 'Back', acts_as_taggable_on_tag_index_path %>